// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package sshd

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type bpfCustomPayload struct {
	RawBuf     [450]uint8
	_          [2]byte
	PayloadLen uint32
}

type bpfSyscallReadLogging struct {
	BufferAddr  uint64
	CallingSize int64
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
}

// bpfSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	HandleCloseExit   *ebpf.ProgramSpec `ebpf:"handle_close_exit"`
	HandleOpenatEnter *ebpf.ProgramSpec `ebpf:"handle_openat_enter"`
	HandleOpenatExit  *ebpf.ProgramSpec `ebpf:"handle_openat_exit"`
	HandleReadEnter   *ebpf.ProgramSpec `ebpf:"handle_read_enter"`
	HandleReadExit    *ebpf.ProgramSpec `ebpf:"handle_read_exit"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	MapBuffAddrs     *ebpf.MapSpec `ebpf:"map_buff_addrs"`
	MapFds           *ebpf.MapSpec `ebpf:"map_fds"`
	MapPayloadBuffer *ebpf.MapSpec `ebpf:"map_payload_buffer"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	MapBuffAddrs     *ebpf.Map `ebpf:"map_buff_addrs"`
	MapFds           *ebpf.Map `ebpf:"map_fds"`
	MapPayloadBuffer *ebpf.Map `ebpf:"map_payload_buffer"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.MapBuffAddrs,
		m.MapFds,
		m.MapPayloadBuffer,
	)
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	HandleCloseExit   *ebpf.Program `ebpf:"handle_close_exit"`
	HandleOpenatEnter *ebpf.Program `ebpf:"handle_openat_enter"`
	HandleOpenatExit  *ebpf.Program `ebpf:"handle_openat_exit"`
	HandleReadEnter   *ebpf.Program `ebpf:"handle_read_enter"`
	HandleReadExit    *ebpf.Program `ebpf:"handle_read_exit"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.HandleCloseExit,
		p.HandleOpenatEnter,
		p.HandleOpenatExit,
		p.HandleReadEnter,
		p.HandleReadExit,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_x86_bpfel.o
var _BpfBytes []byte
